package demo;

import io.github.kinsleykajiva.ffmpeg.FFmpeg;
import io.github.kinsleykajiva.ffmpeg.model.AudioCodec;
import io.github.kinsleykajiva.ffmpeg.model.AudioMetadata;

import java.io.File;

/**
 * Demo for reading (probing) and writing (setting) comprehensive audio metadata.
 */
public class ComprehensiveMetadataDemo {
    public static void main(String[] args) {
        String inputPath = "media-files/song.mp3";
        String outputPath = "media-files/song_with_tags.mp3";
        FFmpeg.setBinPath("C:\\Users\\Kinsley\\IdeaProjects\\ffmpeg-with-java-demo\\ffmpeg-with-java-lib\\ffmpeg-builds\\win64\\bin");
        
        System.out.println("=== FFmpeg Metadata Management Demo ===");

        try {
            // 1. Read existing metadata
            System.out.println("\n[1] Reading current metadata from: " + inputPath);
            AudioMetadata originalMeta = FFmpeg.input(inputPath).probe();
            printMetadata(originalMeta);

            // 2. Set new metadata while transcoding (or just copying)
            System.out.println("\n[2] Setting new metadata and saving to: " + outputPath);
            FFmpeg.input(inputPath)
                .output(outputPath)
                .withCodec(AudioCodec.LIBMP3LAME) // Ensure we use a codec that supports metadata
                .withMetadata("title", "Modern Java FFmpeg Anthem")
                .withMetadata("artist", "The Panama Group")
                .withMetadata("album", "High Performance Audio")
                .withMetadata("comment", "Generated by Modern FFmpeg Java library using Java 25")
                .withMetadata("date", "2026")
                .execute();

            // 3. Verify the changes
            System.out.println("\n[3] Verifying new metadata from: " + outputPath);
            AudioMetadata updatedMeta = FFmpeg.input(outputPath).probe();
            printMetadata(updatedMeta);

        } catch (Exception e) {
            System.err.println("Metadata demo failed: " + e.getMessage());
        }
    }

    private static void printMetadata(AudioMetadata metadata) {
        System.out.println("  Format: " + metadata.format());
        System.out.println("  Common Tags:");
        System.out.println("    Title: " + metadata.tags().getOrDefault("title", "N/A"));
        System.out.println("    Artist: " + metadata.tags().getOrDefault("artist", "N/A"));
        System.out.println("    Album: " + metadata.tags().getOrDefault("album", "N/A"));
        System.out.println("    Comment: " + metadata.tags().getOrDefault("comment", "N/A"));
    }
}
